name: Update README Every Minute

on:
  schedule:
    - cron: '*/10 * * * *'  # Every minute
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This is the key fix - allows pushing commits
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # keeps the token for pushing
          token: ${{ secrets.GITHUB_TOKEN }}  # Explicitly use GitHub token
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Run Python script
        run: python main.py
      
      - name: Commit and push changes
        run: |
          git config user.name "yasandu0505"
          git config user.email "yasanduyaka2005@gmail.com"
          git add README.md
          git commit -m "🤖 Update README timestamp" || echo "No changes to commit"
          git push --force