name: Download PDFs

on:
  schedule:
    - cron: '* */2 * * *'  # Every 2 hours (adjust as needed)
  workflow_dispatch:  # Allow manual trigger

jobs:
  download-pdfs:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow pushing commits
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          pip install requests
      
      - name: Download PDFs
        run: python main.py
      
      - name: Commit and push changes
        run: |
          git config user.name "yasandu0505"
          git config user.email "yasanduyaka2005@gmail.com"
          git add .
          git commit -m "📄 Automated PDF download - $(date)" || echo "No changes to commit"
          git push